name: test

defaults:
  run:
    shell: bash -leo pipefail {0}

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: self-hosted
    strategy:
      matrix:
        destination: [
          'macOS', 
          'iOS Simulator,name=iPhone 15,OS=17.5', 
          'tvOS Simulator,name=Apple TV,OS=17.5', 
          'watchOS Simulator,name=Apple Watch Series 9 (41mm),OS=10.5'
        ]
        xcode: [
          '15.4',
          '16.2',
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Gems
        run: bundle install
      - name: Run tests
        env:
          DESTINATION: platform=${{ matrix.destination }}
          XCODE_VERSION: ${{ matrix.xcode }}
        run: bundle exec fastlane test_ci
